cart/urls.py
from django.urls import path

from .views import CartPage, add_to_cart, add_to_cart_custom_collection, \
    remove_from_cart, checkout_request, Checkout, checkout_complete

app_name = 'cart'

urlpatterns = [
    path('', CartPage.as_view(), name="view"),

    path('add/custom-collection/<slug>/', add_to_cart_custom_collection, name="add_to_cart_custom_collection"),
    path('add/<slug>/', add_to_cart, name="add_to_cart"),

    path('remove/<slug>/', remove_from_cart, name="remove_from_cart"),

    path('checkout/', checkout_request, name="checkout_request"),
    path('checkout/confirm/', Checkout.as_view(), name="checkout_confirm"),
    path('checkout/complete/<order_code>/', checkout_complete, name="checkout_complete"),
]

macalicious/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.utils.html import mark_safe

from shop.sitemap import MacaronSetSitemap, MacaronCollectionSitemap
from .sitemap import StaticViewSitemap
from .views import LandingPage, TOSPage, CustomRegistrationView

sitemaps = {
    'static': StaticViewSitemap,
    'macaron_sets': MacaronSetSitemap,
    'macaron_collections': MacaronCollectionSitemap,
}

urlpatterns = [
                  path('admin/', admin.site.urls),  # admin panel endpoint

                  path('', LandingPage.as_view(), name="landing"),

                  # TODO: Removed about for temporary deployment
                  # path('about/', AboutPage.as_view(), name="about"),

                  path('tos/', TOSPage.as_view(), name="tos"),

                  path('contact/', include('contact.urls')),  # contact app endpoint
                  path('shop/', include('shop.urls')),  # shop app endpoint
                  path('newsletter/', include('newsletter.urls')),  # newsletter app endpoint
                  path('cart/', include('cart.urls')),  # cart app endpoint
                  path('orders/', include('orders.urls')),  # orders app endpoint
                  path('account/', include('account.urls')),
                  path('search/', include('search.urls')),

                  # account urls
                  path('accounts/register/', CustomRegistrationView.as_view(), name='registration_register'),
                  path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name="login"),
                  path('accounts/', include('registration.backends.default.urls')),

                  # sitemap
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="sitemap"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = mark_safe(f"<b>Macalicious Admin</b>")
admin.site.site_title = mark_safe(f"Macalicious Admin Portal")
admin.site.index_title = mark_safe(f"Welcome to Macalicious Admin")

orders/urls.py
from django.urls import path

from.views import OrdersPage


app_name = 'orders'

urlpatterns = [
    path('', OrdersPage.as_view(), name="view"),
]

shop/urls.py
from django.urls import path

from .views import ShopPage, SetsPage, CollectionsPage, SetDetailPage, CollectionDetailPage, CustomCollectionPage


app_name = 'shop'

urlpatterns = [
    path('', ShopPage.as_view(), name="view"),
    path('macarons/', SetsPage.as_view(), name="sets"),
    path('collections/', CollectionsPage.as_view(), name="collections"),
    path('set/<slug>/', SetDetailPage.as_view(), name="set_detail"),
    path('collection/<slug>/', CollectionDetailPage.as_view(), name="collection_detail"),

    # create custom collection
    path('collection/create/<slug>/', CustomCollectionPage.as_view(), name='custom_collection'),
]

cart/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import CartItem


class AddToCartForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = [
            'quantity'
        ]

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        if quantity <= 0 or quantity > 25:
            raise ValidationError("Quantity error")
        return quantity

cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse, get_object_or_404, HttpResponse
from django.template.loader import render_to_string
from django.utils.html import mark_safe, strip_tags
from django.views.generic import View

from macalicious.utils import random_string_generator, handle_recaptcha_response
from orders.models import Order
from shop.models import Set, Macaron, CustomCollectionType, CustomCollection
from .forms import AddToCartForm
from .models import Cart, CartItem


# custom collection add to cart
@login_required
def add_to_cart_custom_collection(request, slug):
    if request.method == "POST":
        item_type = request.POST.get('item_type')
        custom_collection_type = get_object_or_404(CustomCollectionType,
                                                   slug=slug)
        if custom_collection_type:
            if item_type == 'customcollection':
                # get macarons
                macarons_list_raw = request.POST.getlist('macarons')
                [macarons_list] = [item.split(',') for item in macarons_list_raw]
                macarons = []
                for item in macarons_list:
                    macarons.append(get_object_or_404(Macaron, slug=item))
                if len(macarons) == custom_collection_type.quantity_flavour:
                    # the quantity of each flavor is valid and the item_type is valid
                    # create customcollection object and save macarons to it
                    custom_collection = CustomCollection.objects.create(
                        user=request.user,
                        type=custom_collection_type,
                    )
                    custom_collection.macarons.set(macarons)
                    custom_collection.save()

                    if custom_collection:
                        # custom collection has been added - now add the custom collection to the cart
                        cart_instance = get_or_create_cart(request)

                        try:
                            item_type_instance = ContentType.objects.get(model=item_type)
                        except ContentType.DoesNotExist:
                            messages.add_message(request, messages.ERROR, 'Content Type does not exist')
                            return redirect(
                                reverse('shop:custom_collection', kwargs={'slug': custom_collection_type.slug}))

                        # CustomCollection
                        Klass = item_type_instance.model_class()
                        object_instance = Klass.objects.get(slug=custom_collection.slug)
                        object_id = object_instance.id

                        object_name = get_object_name(item_type=item_type_instance,
                                                      object_instance=object_instance)

                        # check add_to_cart form for item quantity
                        add_to_cart_form = AddToCartForm(data=request.POST)
                        if add_to_cart_form.is_valid():
                            # create the CartItem instance
                            cart_item = add_to_cart_form.save(commit=False)
                            cart_item.cart = cart_instance
                            cart_item.item_type = item_type_instance
                            cart_item.object_id = object_id
                            cart_item.total = cart_item.get_total()
                            cart_item.cart.user = request.user
                            cart_item.save()
                            print('cart item : ', cart_item)
                            messages.add_message(request, messages.INFO, mark_safe(
                                f"<i class='bi bi-cart-check'></i>&nbsp; <span class='fancy'>{object_name}</span>&nbsp;has been added to your cart."))
                            return redirect(reverse('cart:view'))
                        else:
                            print('Add to cart item quantity is invalid')
                            messages.add_message(request, messages.ERROR,
                                                 'Enter a quantity between 1 and 25. Please try again.')
                            return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
                    else:
                        print('Custom Collection creation error.')
                        messages.add_message(
                            request, messages.ERROR,
                            'Something went wrong. Please try again later.')
                        return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
                else:
                    # the length of the flavours chosen is not valid
                    print('Custom collection form array length error.')
                    messages.add_message(request, messages.ERROR,
                                         'Something went wrong. Please try again later.')
                    return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
            else:
                messages.add_message(request, messages.ERROR,
                                     'Something went wrong. Please try again later.')
                return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
        else:
            # custom collection type doesn't exist
            print('custom collection type doesn\'t match.')
            messages.add_message(request, messages.ERROR, 'Something went wrong. Please try again later.')
            return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
    else:
        print('request method error')
        messages.add_message(request, messages.ERROR, 'Something went wrong. Please try again later.')
        return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))


# add macaron set or collection to the cart
# if a cart instance is not saved in request.session, create a new cart instance
def add_to_cart(request, slug):
    if request.method == "POST":
        # Check if the quantity of the item being added is valid
        if int(request.POST.get('quantity')) > 0:
            cart_instance = get_or_create_cart(request)
            try:
                # Get the contenttype instance type
                item_type = ContentType.objects.get(model=request.POST.get('item_type'))
            except ContentType.DoesNotExist:
                messages.add_message(request, messages.ERROR, f"Something went wrong. Please try again later.")
                return redirect(reverse('cart:view'))
            # get the model class from the contenttype instance type
            Klass = item_type.model_class()
            # get the object based on the slug provided
            object_instance = Klass.objects.get(slug=slug)
            object_id = object_instance.id

            # get the object name being added to the cart.
            object_name = get_object_name(item_type=request.POST.get('item_type'), object_instance=object_instance)

            add_to_cart_form = AddToCartForm(data=request.POST)
            if add_to_cart_form.is_valid():
                # create the CartItem instance
                cart_item = add_to_cart_form.save(commit=False)
                # add cart item details
                cart_item.cart = cart_instance
                cart_item.item_type = item_type
                cart_item.object_id = object_id
                cart_item.total = cart_item.get_total()
                # check if user is logged in
                if request.user.is_authenticated:
                    # associate logged in user to cart
                    cart_item.cart.user = request.user
                cart_item.save()
                messages.add_message(request, messages.INFO, mark_safe(
                    f"<i class='bi bi-cart-check'></i>&nbsp; <span class='fancy'>{object_name}</span> has been added to your cart."))
                return redirect(reverse('cart:view'))
            else:
                # Adding to cart is invalid
                print('object type: ', item_type.name)
                print(object_instance.slug)
                messages.add_message(request, messages.ERROR,
                                     mark_safe(
                                         f"Enter a quantity between 1 and 25. Please try again."))
                if item_type.name == 'Macaron Collection':
                    return redirect(reverse('shop:collection_detail', kwargs={'slug': object_instance.slug}))
                elif item_type.name == 'Macaron Set':
                    return redirect(reverse('shop:set_detail', kwargs={'slug': object_instance.slug}))
                else:
                    return redirect(reverse('shop:view'))
        else:
            # Quantity is invalid.
            messages.add_message(request, messages.ERROR, f"Please choose a valid quantity. One or more required.")
            return redirect(reverse('shop:view'))
    else:
        # GET request is invalid
        messages.add_message(request, messages.ERROR, f"Something went wrong. Please try again later.")
        return redirect(reverse('shop:view'))


# Get cart stored in request.session or create a cart and store it in request.session
def get_or_create_cart(request):
    if request.session.get('cart'):
        try:
            cart = Cart.objects.get(id=request.session['cart'])
        except Cart.DoesNotExist:
            cart = None
    else:
        cart = Cart.objects.create()
        if cart:
            request.session['cart'] = cart.id
    return cart


# Get the object name (macaron set or collection) being added to the cart.

cart/templates/cart/checkout_complete.html
{% extends "master.html" %}
{% load i18n %}

{% block head_title %}
    Order Placed
{% endblock %}

{% block content %}

    <div class="row justify-content-md-center">
        <div class="col-md-6 col-sm-12 col-xs-12">

            <h1>Order Placed</h1>
            <hr>

            {% include 'partials/messages.html' %}

            {% if order %}

                <h3>Order Summary</h3>

                <div class="mt-3 order-summary-details">
                    <p style="font-size: 16px;">
                        <b>Order:</b> <span>{{ order.code }}</span> <br>
                        <b>Date: </b><span>{{ order.created_at }}</span> <br>
                        <b>Total: </b><span>${{ order.total }} &nbsp;&middot;&nbsp; {{ order.cart.cart_items.active.count }}{% if order.cart.cart_items.count == 1 %} item. {% else %} items. {% endif %}</span>
                        <br>
                        Payment due upon pickup. <br>
                        Cash and Interac E-transfer accepted.
                    </p>
                    <hr>
                    <p class="mt-2 fw-bold">
                        {% if order.user.get_full_name %}
                            {{ order.user.get_full_name }}
                        {% else %}
                            {{ order.user.username }}
                        {% endif %}
                    </p>
                    <p>
                        {{ order.user.profile.phone_number.as_national }}
                    </p>
                    <p>{{ order.user.email }}</p>
                </div>

                <div class="row row-cols-1 row-cols-md-2 g-4 mt-0">
                    {% include 'partials/cart_results.html' with cart_items=order.cart.cart_items.all completed=True %}
                </div>

                <a href="{% url 'orders:view' %}" class="btn btn-outline-primary mt-4">My Orders &nbsp;<i class="bi bi-arrow-right"></i></a>

            {% else %}

                <p>
                    {% trans "Something went wrong. We can't display your order details right now. Please try again later." %}
                </p>

            {% endif %}


        </div>
    </div>


{% endblock %}

cart/templates/cart/checkout_confirm.html
{% extends "master.html" %}
{% load i18n %}

{% block head_title %}
    Confirm Your Order
{% endblock %}

{% block content %}

    <div class="row justify-content-md-center">
        <div class="col-md-6 col-sm-12 col-xs-12">


            <h1>Confirm Your Order</h1>
            <hr>

            {% include 'partials/messages.html' %}

            {% if order %}

                <div class="row row-cols-1 row-cols-md-2 g-4">
                    {% include 'partials/cart_results.html' with cart_items=order.cart.cart_items.all %}
                </div>

                <hr class="regular">

                <div class="d-flex justify-content-end">

                    <div class="text-end price" style="font-size: 24px;">
                        {% if order.tax == 0 %}
                            <p><b>Order Total:</b> ${{ order.total|floatformat:2 }}</p>
                        {% else %}
                            <p><b>Cart Total: </b>${{ order.cart.total|floatformat:2 }}</p>
                            <p><b>Sales Tax: </b>${{ order.get_tax_amount|floatformat:2 }}</p>
                            <p><b>Order Total:</b> ${{ order.total|floatformat:2 }}</p>
                        {% endif %}
                    </div>

                </div>

                <div class="d-flex justify-content-md-between justify-content-end">
                    <div class="d-none d-md-block d-lg-block">
                        <a href="{% url 'cart:view' %}" class="btn btn-outline-secondary">
                            <i class="bi bi-chevron-left"></i> &nbsp;Back to Cart &nbsp;<i class="bi bi-cart"></i>
                        </a>
                    </div>
                    {% include 'partials/confirm_checkout.html' %}
                </div>

            {% else %}

                <p>{% trans "Sorry, something went wrong. We can't find your order details." %}</p>

            {% endif %}


        </div>
    </div>

{% endblock %}

cart/templates/cart/view.html
{% extends "master.html" %}

{% block head_title %}
    Cart
{% endblock %}

{% block content %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-md-12 col-sm-12 col-xs-12">

                <div class="d-flex justify-content-between">
                    <h1 class="mb-0">Cart</h1>
                    {% if cart.cart_items.count %}
                        <div class="d-flex align-items-center">
                        <span class="text-muted price" style="font-size:18px;">{{ cart.cart_items.count }}
                            {% if cart.cart_items.count == 1 %}
                                item{% else %}items{% endif %}</span>
                        </div>
                    {% endif %}
                </div>

                <hr>

                {% include 'partials/messages.html' %}

                {% if cart %}

                    {% if cart.cart_items.active.count == 0 %}

                        <div class="alert alert-info">
                            There are no items in your cart. &nbsp;<a href="{% url 'shop:view' %}" class="email-link">Visit
                            our shop</a>.
                        </div>

                    {% else %}

                        <div class="row row-cols-1 row-cols-md-2 g-4">

                            {% include 'partials/cart_results.html' with cart_items=cart.cart_items.all %}

                        </div>

                        <hr class="regular">

                        <div class="mt-3 d-flex justify-content-between">
                            <div class="text-muted">
                                Sales tax may be applied at checkout.
                            </div>
                            <div>
                                <span class="price" style="font-size:24px;">Total:&nbsp; ${{ cart.total }}</span>
                            </div>
                        </div>

                        <div class="d-flex justify-content-between mt-3">

                            <div class="d-flex align-items-center">
                                <a href="{% url 'shop:view' %}" class="btn btn-outline-secondary"><i
                                        class="bi bi-chevron-left"></i> &nbsp;Continue Shopping</a>
                            </div>

                            {% include 'partials/request_checkout.html' %}

                        </div>

                    {% endif %}


                    {% if recommended_macaron_sets %}

                        <div class="mt-4">
                            <h3>You might{% if cart.cart_items.all %} also {% endif %} like</h3>

                            <div class="row row-cols-1 row-cols-md-2 g-4">
                                {% for set in recommended_macaron_sets %}

                                    {% include 'partials/set_results.html' with set=set %}

                                {% endfor %}
                            </div>
                        </div>

                    {% endif %}


                {% else %}

                    <p>Something went wrong while trying to create a cart for you.</p>

                {% endif %}


            </div>
        </div>
    </div>

{% endblock %}