cart/urls.py
from django.urls import path

from .views import CartPage, add_to_cart, add_to_cart_custom_collection, \
    remove_from_cart, checkout_request, Checkout, checkout_complete

app_name = 'cart'

urlpatterns = [
    path('', CartPage.as_view(), name="view"),

    path('add/custom-collection/<slug>/', add_to_cart_custom_collection, name="add_to_cart_custom_collection"),
    path('add/<slug>/', add_to_cart, name="add_to_cart"),

    path('remove/<slug>/', remove_from_cart, name="remove_from_cart"),

    path('checkout/', checkout_request, name="checkout_request"),
    path('checkout/confirm/', Checkout.as_view(), name="checkout_confirm"),
    path('checkout/complete/<order_code>/', checkout_complete, name="checkout_complete"),
]

contact/urls.py
from django.urls import path

from .views import ContactPage

app_name = 'contact'

urlpatterns = [
    path('', ContactPage.as_view(), name="view"),
]

macalicious/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.utils.html import mark_safe

from shop.sitemap import MacaronSetSitemap, MacaronCollectionSitemap
from .sitemap import StaticViewSitemap
from .views import LandingPage, TOSPage, CustomRegistrationView

sitemaps = {
    'static': StaticViewSitemap,
    'macaron_sets': MacaronSetSitemap,
    'macaron_collections': MacaronCollectionSitemap,
}

urlpatterns = [
                  path('admin/', admin.site.urls),  # admin panel endpoint

                  path('', LandingPage.as_view(), name="landing"),

                  # TODO: Removed about for temporary deployment
                  # path('about/', AboutPage.as_view(), name="about"),

                  path('tos/', TOSPage.as_view(), name="tos"),

                  path('contact/', include('contact.urls')),  # contact app endpoint
                  path('shop/', include('shop.urls')),  # shop app endpoint
                  path('newsletter/', include('newsletter.urls')),  # newsletter app endpoint
                  path('cart/', include('cart.urls')),  # cart app endpoint
                  path('orders/', include('orders.urls')),  # orders app endpoint
                  path('account/', include('account.urls')),
                  path('search/', include('search.urls')),

                  # account urls
                  path('accounts/register/', CustomRegistrationView.as_view(), name='registration_register'),
                  path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name="login"),
                  path('accounts/', include('registration.backends.default.urls')),

                  # sitemap
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="sitemap"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = mark_safe(f"<b>Macalicious Admin</b>")
admin.site.site_title = mark_safe(f"Macalicious Admin Portal")
admin.site.index_title = mark_safe(f"Welcome to Macalicious Admin")

shop/urls.py
from django.urls import path

from .views import ShopPage, SetsPage, CollectionsPage, SetDetailPage, CollectionDetailPage, CustomCollectionPage


app_name = 'shop'

urlpatterns = [
    path('', ShopPage.as_view(), name="view"),
    path('macarons/', SetsPage.as_view(), name="sets"),
    path('collections/', CollectionsPage.as_view(), name="collections"),
    path('set/<slug>/', SetDetailPage.as_view(), name="set_detail"),
    path('collection/<slug>/', CollectionDetailPage.as_view(), name="collection_detail"),

    # create custom collection
    path('collection/create/<slug>/', CustomCollectionPage.as_view(), name='custom_collection'),
]

shop/models.py
from django.db import models
from django.shortcuts import reverse
from django.utils.html import mark_safe
from django.conf import settings

from .managers import TagManager, MacaronManager, ImageManager, SetManager, \
    CollectionItemManager, CollectionManager, CollectionImageManager, \
    CustomCollectionTypeManager, CustomCollectionManager

TAG_CHOICES = (
    ('Vegan', 'Vegan'),
    ('Gluten Free', 'Gluten Free'),
    ('Halal', 'Halal'),
    ('Nut Free', 'Nut Free')
)


class Tag(models.Model):
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    name = models.CharField(max_length=40, choices=TAG_CHOICES, unique=True)
    slug = models.SlugField(blank=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = TagManager()

    def __str__(self) -> str:
        return f"{self.name}"

    def save(self, *args, **kwargs):
        # if tag is set to inactive, remove tag from association with macaron
        if not self.active:
            self.macaron_set.clear()
        super(Tag, self).save(*args, **kwargs)


class Macaron(models.Model):
    class Meta:
        verbose_name = 'Macaron'
        verbose_name_plural = 'Macarons'

    name = models.CharField(max_length=120)
    description = models.TextField(max_length=5000)
    tags = models.ManyToManyField(Tag, limit_choices_to={"active": True}, blank=True)
    active = models.BooleanField(default=True)
    slug = models.SlugField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = MacaronManager()

    def __str__(self) -> str:
        return f"{self.name}"

    def get_macaron_tags(self):
        output = ''
        for item in self.tags.all():
            output += f"<li>{item.name}</li>"
        return mark_safe(output)
        # Output tags in a single line separated by a ','
        # for index, item in enumerate(self.tags.all()):
        #     output += item.name
        #     if index != len(self.tags.all()) - 1:
        #         output += ', '
        # return output

    get_macaron_tags.short_description = 'Tags'

    def get_short_description(self):
        return self.description.split('.')[0]


class Image(models.Model):
    class Meta:
        verbose_name = 'Macaron Image'
        verbose_name_plural = 'Macaron Images'

    macaron = models.ForeignKey(Macaron, on_delete=models.CASCADE, related_name='images')
    picture = models.ImageField(upload_to='macarons/images/')
    alt_text = models.CharField(max_length=120)
    caption = models.TextField(max_length=5000)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = ImageManager()

    def __str__(self):
        return f"{self.macaron.name}'s Image"


class Set(models.Model):
    class Meta:
        verbose_name = 'Macaron Set'
        verbose_name_plural = 'Macaron Sets'

    macaron = models.ForeignKey(Macaron, on_delete=models.CASCADE, limit_choices_to={"active": True})
    quantity = models.IntegerField(default=6, help_text="Number of macarons per box.")
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0.0,
                                help_text="Price of <b>each</b> macaron. <b>NOT</b> price of entire box.")
    sale_price = models.DecimalField(max_digits=5, decimal_places=2, default=0.0,
                                     help_text="Price of <b>each</b> macaron. <b>NOT</b> price of entire box.")
    active = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    slug = models.SlugField(blank=True)
    order = models.PositiveIntegerField(default=0, verbose_name="Display Order")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = SetManager()

    def __str__(self) -> str:
        return f"{self.macaron.name} | {self.quantity} for ${self.get_total()}"

    def get_absolute_url(self):
        return reverse('shop:set_detail', kwargs={'slug': self.slug})

    def get_name(self) -> str:
        return f"{self.macaron.name}"

    get_name.short_description = "Macaron"

    def get_all_images(self):
        return self.macaron.images.all()

    def get_featured_image(self):
        return self.macaron.images.featured()

    def get_description(self):
        return f"{self.macaron.description}"

    # Get the price of each maracon
    @property
    def get_price(self):
        if self.sale_price < self.price and self.sale_price != 0:
            return self.sale_price
        return self.price

    def get_original_price(self):
        return self.quantity * self.price

    def display_price(self):
        if self.is_on_sale():
            return mark_safe(
                f"<span style='color:#b53211;'>&nbsp;${self.get_total()}</span> &nbsp;")
        else:
            return mark_safe(f"<span>${self.get_total()}</span>")

    def is_on_sale(self):
        if self.sale_price < self.price and self.sale_price != 0:
            return True
        return False

    # Get price of the macarons and the final price (original price or sale price)
    def get_total(self):
        return self.quantity * self.get_price

    def display_total(self):
        if self.is_on_sale():
            return mark_safe(
                f"<span class='price' style='font-size:18px;text-decoration:line-through;'>&nbsp;${self.get_original_price()}&nbsp;</span> &nbsp;"
                f"<span class='price' style='font-size:21px;color:#91363d;'>${self.get_total()}</span>")
        else:
            return mark_safe(f"<span class='price' style='font-size:21px;'>${self.get_total()}</span>")

    def admin_get_price(self):
        return self.price

    admin_get_price.short_description = "Price - Each"

    def admin_sale_price(self):
        if self.sale_price > 0:
            return mark_safe(f"<span style='font-weight:bold; color:#fb523b;'>${self.sale_price}</span>")
        return '-'

    admin_sale_price.short_description = "Sale Price - Each"

    def admin_get_total(self):
        if self.sale_price > 0:
            return mark_safe(f"<span style='font-weight:bold;font-size:14px;color:#fb523b;'>${self.get_total()}</span>")
        return mark_safe(f"<span style='font-weight:bold;font-size:14px;'>${self.get_total()}</span>")

    admin_get_total.short_description = mark_safe(
        "<span style='text-decoration:underline;'>Set Total Price</span>"
    )


class CollectionItem(models.Model):
    class Meta:
        verbose_name = 'Macaron Collection Item'
        verbose_name_plural = 'Macaron Collection Items'

    macaron = models.ForeignKey(Macaron, on_delete=models.CASCADE, limit_choices_to={"active": True})
    quantity = models.IntegerField(default=3)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CollectionItemManager()

    def __str__(self) -> str:
        return f"{self.macaron.name}"

    def admin_collection_list(self) -> str:
        output = ""
        for collection in self.macaroncollection_set.all():
            output += f"<li>{collection.name}</li>"
        return mark_safe(output)

    admin_collection_list.short_description = "In Collections"


class Collection(models.Model):
    class Meta:
        verbose_name = 'Macaron Collection'
        verbose_name_plural = 'Macaron Collections'

    name = models.CharField(max_length=120)
    macarons = models.ManyToManyField(CollectionItem, limit_choices_to={"active": True})
    description = models.TextField(max_length=5000)
    price = models.DecimalField(max_digits=5, decimal_places=2, help_text="Price for entire collection.", default=0.0)
    sale_price = models.DecimalField(max_digits=5, decimal_places=2, default=0.00,
                                     help_text="Discounted price for entire collection.")
    active = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    slug = models.SlugField(blank=True)
    order = models.PositiveIntegerField(default=0, verbose_name="Display Order")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CollectionManager()

    def __str__(self) -> str:
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('shop:collection_detail', kwargs={'slug': self.slug})

    def get_name(self) -> str:
        return self.name

    def get_all_images(self):
        return self.images.all()

    def get_featured_image(self):
        return self.images.featured()

    def get_description(self) -> str:
        return self.description

    def get_short_description(self) -> str:
        return self.description.split('.')[0]

    def get_macaron_count(self):
        total = 0
        for item in self.macarons.all():
            total += item.quantity
        return total

    def get_macaron_list(self) -> str:
        output = ''
        for item in self.macarons.all():
            output += f"{item.macaron.name} &nbsp;(<b>{item.quantity}</b>)<br />"
        return mark_safe(output)

    get_macaron_list.short_description = "Macaron List"

    # Get the price of the collection (original price or sale price)
    @property
    def get_price(self):
        if self.is_on_sale():
            return self.sale_price
        return self.price

    def get_original_price(self):
        return self.price

    def get_total(self):
        return self.get_price

    def display_price(self):
        if self.is_on_sale():
            return mark_safe(f"<span style='color:#b53211;'>${self.get_total()}</span>")
        else:

shop/forms.py
from django import forms

# from .models import Macaron
#
#
# class CustomCollectionForm(forms.Form):
#     # macarons = forms.ModelMultipleChoiceField(queryset=Macaron.objects.all())
#     macarons = forms.MultipleChoiceField(queryset=Macaron.objects.all())

shop/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic import View
from django.conf import settings

from cart.forms import AddToCartForm

from .models import Set, Collection, Macaron, CustomCollection, CustomCollectionType


# macarons page endpoint [url: /shop/macarons/]
class SetsPage(ListView):
    template_name = 'shop/sets.html'
    model = Set
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(shop_context())
        return context


# macarons page endpoint [url: /shop/collections/]
class CollectionsPage(ListView):
    template_name = 'shop/collections.html'
    model = Collection
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(shop_context())
        return context


# sets page and collections page context
def shop_context():
    return {
        'add_to_cart_form': AddToCartForm(),
        'custom_collection_types': CustomCollectionType.objects.all()
    }


# Shop page endpoint [url: /shop/]
class ShopPage(View):
    template_name = 'shop/view.html'

    def get(self, request):
        macaron_sets = Set.objects.featured()[:3]
        macaron_collections = Collection.objects.featured()[:3]
        custom_collection_types = CustomCollectionType.objects.all()
        context = {
            'macaron_sets': macaron_sets,
            'macaron_collections': macaron_collections,
            'add_to_cart_form': AddToCartForm(),
            'custom_collection_types': custom_collection_types,
        }
        return render(request, self.template_name, context)


class SetDetailPage(View):
    template_name = 'shop/set_detail.html'

    def get(self, request, slug):
        macaron_set = get_object_or_404(Set, slug=slug)
        macaron_recommended_sets = Set.objects.recommended()
        context = {
            'macaron_set': macaron_set,
            'add_to_cart_form': AddToCartForm(),
            'macaron_recommended_sets': macaron_recommended_sets,
        }
        return render(request, self.template_name, context)


class CollectionDetailPage(View):
    template_name = 'shop/collection_detail.html'

    def get(self, request, slug):
        macaron_collection = get_object_or_404(Collection, slug=slug)
        macaron_recommended_collections = Collection.objects.recommended()
        context = {
            'macaron_collection': macaron_collection,
            'add_to_cart_form': AddToCartForm(),
            'macaron_recommended_collections': macaron_recommended_collections,
        }
        return render(request, self.template_name, context)


class CustomCollectionPage(LoginRequiredMixin, View):
    template_name = 'shop/custom_collection.html'

    def get(self, request, slug):
        custom_collection_type = get_object_or_404(CustomCollectionType, slug=slug)
        macaron_recommended_collections = Collection.objects.recommended()
        macaron_recommended_sets = Set.objects.recommended()
        macarons = Macaron.objects.all()
        context = {
            'macarons': macarons,
            'add_to_cart_form': AddToCartForm(),
            'custom_collection_type': custom_collection_type,
            'macaron_recommended_sets': macaron_recommended_sets,
            'macaron_recommended_collections': macaron_recommended_collections,
        }
        return render(request, self.template_name, context)

shop/templates/partials/collection_disclaimer.html
<div class="alert alert-info {% if not detail_page %}mt-2{% endif %} alert-dismissible fade show">
    Please
    <a href="{% url 'contact:view' %}?reason=custom-order" data-bs-toggle="tooltip"
       data-bs-placement="bottom" class="email-link"
       title="Contact Macalicious">contact</a>
    or
    <a href="mailto:shop.macalicious@gmail.com?subject=Custom Order Inquiry" data-bs-toggle="tooltip"
       data-bs-placement="bottom" class="email-link"
       title="Email Macalicious">email</a>
    for more information or inquiries regarding our collections.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

shop/templates/partials/collection_macarons.html
<div class="px-1">
    {% for item in collection_macarons %}
        <li class="my-2" style="list-style-type:none;">
            <div class="d-flex align-items-center collection-macaron-item">
                <img src="{{ item.macaron.images.featured.picture.url }}"
                     alt="{{ item.macaron.images.featured.alt_text }}"
                     width="70" class="rounded shadow-sm border-tiffany"> &nbsp;&nbsp;&nbsp;
                <h5>
                    {% if quantity_each %}{{ quantity_each }}{% else %}{{ item.quantity }}{% endif %}
                    <span class="text-muted">x</span> {{ item.macaron.name }}
                </h5>
            </div>
        </li>
    {% endfor %}
</div>

shop/templates/partials/collection_results.html
<div class="col-md-4 col-sm-12">
{#    <div class="card border-tiffany">#}
    <div class="card shadow-sm">

        {% include 'partials/images_carousel.html' with images=collection.images.all collection=collection %}

        <div style="transform: rotate(0)">
            <div class="card-body">
                <h4 class="card-title mb-1">{{ collection.name }}</h4>
                <p class="card-text mb-1 px-1">{{ collection.display_total }}
                    &nbsp;&middot;&nbsp;
                    <span class="price"
                          style="font-size:18px;">{{ collection.get_macaron_count }} macarons</span>
                </p>
                {% include 'partials/collection_macarons.html' with collection_macarons=collection.macarons.all %}
                <p class="card-text text-black my-2 px-1">{{ collection.get_short_description }}</p>
                <a href="{% url 'shop:collection_detail' collection.slug %}"
                   class="btn btn-outline-primary stretched-link mt-0">Details &nbsp;<i
                        class="bi bi-chevron-right"></i></a>

            </div>
        </div>
    </div>

</div>

shop/templates/partials/custom_collection_form.html
<div id="custom-collection-form">
    <div class="row row-cols-auto g-4">
        {% for macaron in macarons %}

            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="form-check create-custom-collection">
                    <input type="checkbox" class="custom-collection-checkbox form-check-input"
                           value="{{ macaron.slug }}" name="macarons"
                           data-bs-placement="bottom" data-bs-toggle="tooltip" title="Select {{ macaron.name }}"
                           id="macaron_{{ macaron.slug }}"
                           onclick="macaronCheckboxClickEvent({{ custom_collection_type.quantity_flavour }});">
                    <label for="macaron_{{ macaron.slug }}" class="create-custom-collection-label" style="width: 95%;">
                        {% include 'partials/images_carousel.html' with images=macaron.images.all width="225px" height="225px" page='customcollection' %}
                        <h5 class="text-center fancy name mt-2">{{ custom_collection_type.quantity_each }} <span
                                class="text-muted">x</span> {{ macaron.name }}</h5>
                    </label>
                </div>
            </div>

        {% endfor %}
    </div>
</div>

shop/templates/partials/custom_collection_links.html
{% if custom_collection_types %}
    <div class="custom-collection-links mb-3 d-none d-md-block d-lg-block d-xl-block">
        {% for collection_type in custom_collection_types %}
            <a class="btn btn-outline-primary" href="{% url 'shop:custom_collection' collection_type.slug %}">
                <i class="bi bi-box"></i>&nbsp;&nbsp;Create {{ collection_type.name }} Collection
            </a>
        {% endfor %}
    </div>

    <div class="list-group mb-4 shadow-sm d-md-none mobile-navigation-shop-links d-block d-md-none d-lg-none d-xl-none">
        {% for custom_collection_type in custom_collection_types %}
            <a href="{% url 'shop:custom_collection' custom_collection_type.slug %}" style="font-size: 15px;" class="list-group-item list-group-item-action">
                <i class="bi bi-box purple"></i>&nbsp;&nbsp;Create {{ custom_collection_type.name }}
            </a>
        {% endfor %}
    </div>
{% endif %}

shop/templates/partials/featured_results.html
{# Check to see if macarons collections are passed through #}
{% if macaron_collections %}

    <h1 id="macaron_collections">Featured Collections</h1>
    <hr>

    {% include 'partials/collection_disclaimer.html' %}

    {% include 'partials/custom_collection_links.html' %}

    <div class="row row-cols-1 g-4">
        {% for collection in macaron_collections %}

            {% include 'partials/collection_results.html' %}

        {% endfor %}
    </div>

    <a href="{% url 'shop:sets' %}" class="btn btn-outline-primary mt-3">View All &nbsp;<i
            class="bi bi-arrow-right"></i></a>

{% endif %}

{# Check to see if macarons sets are passed through #}
{% if macaron_sets %}

    <h1 class="mt-4" id="macaron_sets">Featured Sets</h1>
    <hr>

    <div class="row row-cols-1 row-cols-md-2 g-4">
        {# display each macaron in card style #}
        {% for set in macaron_sets %}

            {% include 'partials/set_results.html' %}

        {% endfor %}
    </div>

    <a href="{% url 'shop:collections' %}" class="btn btn-outline-primary mt-3">View All &nbsp;<i
            class="bi bi-arrow-right"></i></a>

{% endif %}

shop/templates/partials/images_carousel.html
<div id="carousel{% if set %}-{{ set.slug }}{% elif collection %}-{{ collection.slug }}{% elif cart and not macaron %}-{{ item.content_object.slug }}{% elif macaron %}-{{ macaron.slug }}{% endif %}"
     class="carousel slide {% if detail_page %}sticky-top top-80{% endif %}" data-bs-touch="true"
     data-bs-interval="true"
     style="{% if width %}width:{{ width }}!important;{% endif %}">

    <div class="carousel-inner rounded shadow-sm" role="listbox">

        {% for image in images %}

            <div class="carousel-item {% if forloop.first %}active{% endif %}" data-bs-interval="10000">

                <img src="{{ image.picture.url }}" alt="{{ image.alt_text }}"
                     title="{{ image.alt_text }}"
                     class="d-block w-100 {% if page == 'customcollection' %}border-tiffany{% endif %}"
                     style="{% if width and height %}width:{{ width }} !important; height:{{ height }}!important;{% endif %}">

            </div>

        {% endfor %}

    </div>
    <button class="carousel-control-prev" type="button"
            data-bs-target="#carousel{% if set %}-{{ set.slug }}{% elif collection %}-{{ collection.slug }}{% elif cart and not macaron %}-{{ item.content_object.slug }}{% elif macaron %}-{{ macaron.slug }}{% endif %}"
            data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button"
            data-bs-target="#carousel{% if set %}-{{ set.slug }}{% elif collection %}-{{ collection.slug }}{% elif cart and not macaron %}-{{ item.content_object.slug }}{% elif macaron %}-{{ macaron.slug }}{% endif %}"
            data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

shop/templates/partials/set_results.html
<div class="col-md-4">
{#    <div class="card border-tiffany">#}
    <div class="card shadow-sm">

        {% include 'partials/images_carousel.html' with images=set.macaron.images.all set=set %}

        <div class="card-body" style="transform: rotate(0);">
            <h4 class="card-title mb-1">{{ set.macaron.name }}</h4>
            <p class="card-text mb-1 px-1">{{ set.display_total }}
                &nbsp;&middot;&nbsp;
                <span class="price" style="font-size:18px;">{{ set.quantity }} per box</span></p>
            <p class="card-text text-black px-1 mb-2">{{ set.macaron.description|truncatewords:30 }}</p>
            <a href="{% url 'shop:set_detail' set.slug %}" class="btn btn-outline-primary stretched-link">Details &nbsp;<i
                    class="bi bi-chevron-right"></i></a>
        </div>
    </div>
</div>