cart/urls.py
from django.urls import path

from .views import CartPage, add_to_cart, add_to_cart_custom_collection, \
    remove_from_cart, checkout_request, Checkout, checkout_complete

app_name = 'cart'

urlpatterns = [
    path('', CartPage.as_view(), name="view"),

    path('add/custom-collection/<slug>/', add_to_cart_custom_collection, name="add_to_cart_custom_collection"),
    path('add/<slug>/', add_to_cart, name="add_to_cart"),

    path('remove/<slug>/', remove_from_cart, name="remove_from_cart"),

    path('checkout/', checkout_request, name="checkout_request"),
    path('checkout/confirm/', Checkout.as_view(), name="checkout_confirm"),
    path('checkout/complete/<order_code>/', checkout_complete, name="checkout_complete"),
]

macalicious/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.utils.html import mark_safe

from shop.sitemap import MacaronSetSitemap, MacaronCollectionSitemap
from .sitemap import StaticViewSitemap
from .views import LandingPage, TOSPage, CustomRegistrationView

sitemaps = {
    'static': StaticViewSitemap,
    'macaron_sets': MacaronSetSitemap,
    'macaron_collections': MacaronCollectionSitemap,
}

urlpatterns = [
                  path('admin/', admin.site.urls),  # admin panel endpoint

                  path('', LandingPage.as_view(), name="landing"),

                  # TODO: Removed about for temporary deployment
                  # path('about/', AboutPage.as_view(), name="about"),

                  path('tos/', TOSPage.as_view(), name="tos"),

                  path('contact/', include('contact.urls')),  # contact app endpoint
                  path('shop/', include('shop.urls')),  # shop app endpoint
                  path('newsletter/', include('newsletter.urls')),  # newsletter app endpoint
                  path('cart/', include('cart.urls')),  # cart app endpoint
                  path('orders/', include('orders.urls')),  # orders app endpoint
                  path('account/', include('account.urls')),
                  path('search/', include('search.urls')),

                  # account urls
                  path('accounts/register/', CustomRegistrationView.as_view(), name='registration_register'),
                  path('accounts/login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name="login"),
                  path('accounts/', include('registration.backends.default.urls')),

                  # sitemap
                  path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name="sitemap"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = mark_safe(f"<b>Macalicious Admin</b>")
admin.site.site_title = mark_safe(f"Macalicious Admin Portal")
admin.site.index_title = mark_safe(f"Welcome to Macalicious Admin")

cart/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from .managers import CartManager, CartItemManager


class Cart(models.Model):
    class Meta:
        verbose_name = 'Cart'
        verbose_name_plural = 'Carts'
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    number_of_items = models.PositiveIntegerField(default=0)
    total = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CartManager()

    def __str__(self):
        return f"Cart ID: {self.id}"

    def display_total(self):
        return mark_safe(f"${self.total}")

    def admin_total(self):
        if self.total > 0:
            return mark_safe(f"<span style='font-size:14px;color:#fb523b;font-weight:bold;'>${self.total}</span>")
        return '-'

    admin_total.short_description = "Total"

    def admin_number_of_items(self):
        return self.number_of_items

    admin_number_of_items.short_description = "Cart Items"

    def admin_cart_items(self):
        output = ""
        for item in self.cart_items.all():
            output += f"<li>{item.content_object.get_name()} &nbsp;({item.quantity})</li>"
        return mark_safe(output)

    admin_cart_items.short_description = "Cart Items"


###
# CartItem needs to be generic in order to add:
#     - MacaronSet
#     - MacaronCollection
###
class CartItem(models.Model):
    class Meta:
        verbose_name = 'Cart Item'
        verbose_name_plural = 'Cart Items'
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name="cart_items")
    item_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("item_type", "object_id")
    quantity = models.PositiveIntegerField(default=1)
    total = models.DecimalField(default=0.0, max_digits=10, decimal_places=2)
    active = models.BooleanField(default=True)
    slug = models.SlugField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    objects = CartItemManager()

    def __str__(self):
        return f"Cart: {self.id}"

    def get_quantity(self):
        return f"Quantity: {self.quantity}"

    def get_total(self):
        return self.quantity * self.content_object.get_total()

    def display_total(self):
        if self.content_object.is_on_sale():
            return mark_safe(f"<span style='color:#b53211;'>${self.get_total()}</span>")
        else:
            return mark_safe(f"<span>${self.get_total()}</span>")

    def display_total_checkout(self):
        return self.quantity

    def admin_cart_item(self):
        return f"CartItem: {self.id}"

    admin_cart_item.short_description = "Item"

    def admin_total(self):
        if self.total > 0:
            return mark_safe(f"<span style='font-size:14px;color:#fb523b;font-weight:bold;'>${self.total}</span>")
        else:
            return 0

    admin_total.short_description = "Total"

    def admin_user(self):
        if self.cart.user:
            return f"{self.cart.user.username}"
        else:
            return '-'

    admin_user.short_description = "User"

    def admin_item_type(self):
        if self.item_type.name == "Macaron Custom Collection":
            return f"{self.content_object.type.name}"
        else:
            return f"{self.item_type.name}"

    admin_item_type.short_description = "Item Type"

cart/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import CartItem


class AddToCartForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = [
            'quantity'
        ]

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        if quantity <= 0 or quantity > 25:
            raise ValidationError("Quantity error")
        return quantity

cart/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.core.mail import send_mail
from django.shortcuts import render, redirect, reverse, get_object_or_404, HttpResponse
from django.template.loader import render_to_string
from django.utils.html import mark_safe, strip_tags
from django.views.generic import View

from macalicious.utils import random_string_generator, handle_recaptcha_response
from orders.models import Order
from shop.models import Set, Macaron, CustomCollectionType, CustomCollection
from .forms import AddToCartForm
from .models import Cart, CartItem


# custom collection add to cart
@login_required
def add_to_cart_custom_collection(request, slug):
    if request.method == "POST":
        item_type = request.POST.get('item_type')
        custom_collection_type = get_object_or_404(CustomCollectionType,
                                                   slug=slug)
        if custom_collection_type:
            if item_type == 'customcollection':
                # get macarons
                macarons_list_raw = request.POST.getlist('macarons')
                [macarons_list] = [item.split(',') for item in macarons_list_raw]
                macarons = []
                for item in macarons_list:
                    macarons.append(get_object_or_404(Macaron, slug=item))
                if len(macarons) == custom_collection_type.quantity_flavour:
                    # the quantity of each flavor is valid and the item_type is valid
                    # create customcollection object and save macarons to it
                    custom_collection = CustomCollection.objects.create(
                        user=request.user,
                        type=custom_collection_type,
                    )
                    custom_collection.macarons.set(macarons)
                    custom_collection.save()

                    if custom_collection:
                        # custom collection has been added - now add the custom collection to the cart
                        cart_instance = get_or_create_cart(request)

                        try:
                            item_type_instance = ContentType.objects.get(model=item_type)
                        except ContentType.DoesNotExist:
                            messages.add_message(request, messages.ERROR, 'Content Type does not exist')
                            return redirect(
                                reverse('shop:custom_collection', kwargs={'slug': custom_collection_type.slug}))

                        # CustomCollection
                        Klass = item_type_instance.model_class()
                        object_instance = Klass.objects.get(slug=custom_collection.slug)
                        object_id = object_instance.id

                        object_name = get_object_name(item_type=item_type_instance,
                                                      object_instance=object_instance)

                        # check add_to_cart form for item quantity
                        add_to_cart_form = AddToCartForm(data=request.POST)
                        if add_to_cart_form.is_valid():
                            # create the CartItem instance
                            cart_item = add_to_cart_form.save(commit=False)
                            cart_item.cart = cart_instance
                            cart_item.item_type = item_type_instance
                            cart_item.object_id = object_id
                            cart_item.total = cart_item.get_total()
                            cart_item.cart.user = request.user
                            cart_item.save()
                            print('cart item : ', cart_item)
                            messages.add_message(request, messages.INFO, mark_safe(
                                f"<i class='bi bi-cart-check'></i>&nbsp; <span class='fancy'>{object_name}</span>&nbsp;has been added to your cart."))
                            return redirect(reverse('cart:view'))
                        else:
                            print('Add to cart item quantity is invalid')
                            messages.add_message(request, messages.ERROR,
                                                 'Enter a quantity between 1 and 25. Please try again.')
                            return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
                    else:
                        print('Custom Collection creation error.')
                        messages.add_message(
                            request, messages.ERROR,
                            'Something went wrong. Please try again later.')
                        return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
                else:
                    # the length of the flavours chosen is not valid
                    print('Custom collection form array length error.')
                    messages.add_message(request, messages.ERROR,
                                         'Something went wrong. Please try again later.')
                    return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
            else:
                messages.add_message(request, messages.ERROR,
                                     'Something went wrong. Please try again later.')
                return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
        else:
            # custom collection type doesn't exist
            print('custom collection type doesn\'t match.')
            messages.add_message(request, messages.ERROR, 'Something went wrong. Please try again later.')
            return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))
    else:
        print('request method error')
        messages.add_message(request, messages.ERROR, 'Something went wrong. Please try again later.')
        return redirect(reverse('shop:custom_collection', kwargs={'slug': slug}))


# add macaron set or collection to the cart
# if a cart instance is not saved in request.session, create a new cart instance
def add_to_cart(request, slug):
    if request.method == "POST":
        # Check if the quantity of the item being added is valid
        if int(request.POST.get('quantity')) > 0:
            cart_instance = get_or_create_cart(request)
            try:
                # Get the contenttype instance type
                item_type = ContentType.objects.get(model=request.POST.get('item_type'))
            except ContentType.DoesNotExist:
                messages.add_message(request, messages.ERROR, f"Something went wrong. Please try again later.")
                return redirect(reverse('cart:view'))
            # get the model class from the contenttype instance type
            Klass = item_type.model_class()
            # get the object based on the slug provided
            object_instance = Klass.objects.get(slug=slug)
            object_id = object_instance.id

            # get the object name being added to the cart.
            object_name = get_object_name(item_type=request.POST.get('item_type'), object_instance=object_instance)

            add_to_cart_form = AddToCartForm(data=request.POST)
            if add_to_cart_form.is_valid():
                # create the CartItem instance
                cart_item = add_to_cart_form.save(commit=False)
                # add cart item details
                cart_item.cart = cart_instance
                cart_item.item_type = item_type
                cart_item.object_id = object_id
                cart_item.total = cart_item.get_total()
                # check if user is logged in
                if request.user.is_authenticated:
                    # associate logged in user to cart
                    cart_item.cart.user = request.user
                cart_item.save()
                messages.add_message(request, messages.INFO, mark_safe(
                    f"<i class='bi bi-cart-check'></i>&nbsp; <span class='fancy'>{object_name}</span> has been added to your cart."))
                return redirect(reverse('cart:view'))
            else:
                # Adding to cart is invalid
                print('object type: ', item_type.name)
                print(object_instance.slug)
                messages.add_message(request, messages.ERROR,
                                     mark_safe(
                                         f"Enter a quantity between 1 and 25. Please try again."))
                if item_type.name == 'Macaron Collection':
                    return redirect(reverse('shop:collection_detail', kwargs={'slug': object_instance.slug}))
                elif item_type.name == 'Macaron Set':
                    return redirect(reverse('shop:set_detail', kwargs={'slug': object_instance.slug}))
                else:
                    return redirect(reverse('shop:view'))
        else:
            # Quantity is invalid.
            messages.add_message(request, messages.ERROR, f"Please choose a valid quantity. One or more required.")
            return redirect(reverse('shop:view'))
    else:
        # GET request is invalid
        messages.add_message(request, messages.ERROR, f"Something went wrong. Please try again later.")
        return redirect(reverse('shop:view'))


# Get cart stored in request.session or create a cart and store it in request.session
def get_or_create_cart(request):
    if request.session.get('cart'):
        try:
            cart = Cart.objects.get(id=request.session['cart'])
        except Cart.DoesNotExist:
            cart = None
    else:
        cart = Cart.objects.create()
        if cart:
            request.session['cart'] = cart.id
    return cart


# Get the object name (macaron set or collection) being added to the cart.

cart/templates/partials/add_to_cart.html
{% load crispy_forms_tags %}

{# Add to cart partial template #}
{# REQUIRED: item_slug [maracron_set or collection instance] #}
<form action="{% url 'cart:add_to_cart' item_slug %}" method="POST">
    {% csrf_token %}
    {{ add_to_cart_form|crispy }}
    <input type="hidden" name="item_type" value="{{ item_type }}">
    <button type="submit" class="btn btn-outline-primary">Add to Cart &nbsp;<i class="bi bi-cart"></i></button>
</form>

cart/templates/partials/add_to_cart_custom_collection.html
{% load crispy_forms_tags %}

<form action="{% url 'cart:add_to_cart_custom_collection' custom_collection_type.slug %}"
      id="add-to-cart-custom-collection-form" method="POST">
    {% csrf_token %}

    {{ add_to_cart_form|crispy }}

    <input type="hidden" name="item_type" value="{{ item_type }}">
    <input type="hidden" name="collection_type" value="{{ item_slug }}">
    <input type="hidden" name="macarons" id="macarons-list" value="">

    <button type="submit" class="btn btn-outline-primary">Add to Cart &nbsp;<i class="bi bi-cart"></i></button>
</form>

cart/templates/partials/cart_results.html
{% for item in cart_items %}

    <div class="col-md-4">
        <div class="card shadow-sm">

            {# cart item for Macaron Custom Collection #}
            {% if item.item_type.name == 'Macaron Custom Collection' %}

                {% include 'partials/images_carousel.html' with images=item.content_object.macaron_images cart=True %}

                <div class="card-body" style="padding-top:10px;">
                    <div class="d-flex justify-content-between">
                        <h4 class="d-flex align-items-center card-title mb-0">{{ item.content_object.get_name }}</h4>
                        {# only display remove from cart button if the order is not done - DO NOT display on checkout completed page #}
                        {% if not completed %}
                            <div class="d-flex align-items-center">
                                {% include 'partials/remove_from_cart.html' with item_slug=item.slug item_name=item.content_object.get_name %}
                            </div>
                        {% endif %}
                    </div>

                    <p class="card-text price mb-1 mt-0" style="font-size:18px;">
                        {{ item.content_object.display_total }}
                        &nbsp;&middot;&nbsp;
                        {{ item.content_object.get_macaron_count }} macarons
                    </p>

                    <div class="mt-2">
                        {% include 'partials/collection_macarons.html' with collection_macarons=item.content_object.macaron_images quantity_each=item.content_object.type.quantity_each %}
                    </div>

                </div>

                {# cart item for Set and Collection #}
            {% else %}

                {% include 'partials/images_carousel.html' with images=item.content_object.get_all_images cart=True %}

                <div class="card-body" style="padding-top: 10px;">
                    <div class="d-flex justify-content-between">
                        <h4 class="d-flex align-items-center card-title mb-0">{{ item.content_object.get_name }}</h4>
                        {% if not completed %}
                            <div class="d-flex align-items-center">
                                {% include 'partials/remove_from_cart.html' with item_slug=item.slug item_name=item.content_object.get_name %}
                            </div>
                        {% endif %}
                    </div>

                    <p class="card-text price mb-1 mt-0" style="font-size:18px;">
                        {{ item.content_object.display_total }}
                        &nbsp;&middot;&nbsp;
                        {% if item.item_type.name == 'Macaron Set' %}
                            {{ item.content_object.quantity }} per box
                        {% elif item.item_type.name == 'Macaron Collection' %}
                            {{ item.content_object.get_macaron_count }} macarons
                        {% endif %}
                    </p>
                    {% if item.item_type.name == 'Macaron Set' %}
                        <p class="card-text mb-0">
                            {{ item.content_object.macaron.get_short_description }}
                        </p>
                    {% elif item.item_type.name == 'Macaron Collection' %}
                        <div class="mt-2">
                            {% include 'partials/collection_macarons.html' with collection_macarons=item.content_object.macarons.all %}
                        </div>
                    {% endif %}
                </div>
            {% endif %}
            <div class="card-footer d-flex justify-content-between border-top-tiffany">
                <div class="price" style="font-size:18px;">
                    ${{ item.total }}
                </div>
                <span class="badge rounded-pill bg-primary d-flex align-items-center px-3" style="font-size:11px;">
                    {{ item.quantity }}
                </span>
            </div>
        </div>
    </div>

{% endfor %}

cart/templates/partials/cart_sidebar.html
<div class="px-3 py-4 rounded shadow-sm border sticky-top add-to-cart-sidebar border-tiffany top-80"
     style="background-color: #f8f9fa;">

    <h3>Add to Cart</h3>
    <hr class="my-2">

    {% if item_name and item_price %}

        <div class="d-flex justify-content-between align-items-center">
            <div class="col-8">
                <h5 class="mb-0">{{ item_name }}</h5>
            </div>
            <div class="col-3 text-end">
                <span class="price" style="font-size:21px;">{{ item_price }}</span>
            </div>
        </div>

    {% endif %}

    <div class="mt-1">
        {% if page %}
            {% if page == 'set_detail' %}
                {% include 'partials/add_to_cart.html' with item_slug=macaron_set.slug item_type="set" %}
            {% elif page == 'collection_detail' %}
                {% include 'partials/add_to_cart.html' with item_slug=macaron_collection.slug item_type="collection" %}
            {% elif page == 'custom_collection' %}
                {% include 'partials/add_to_cart_custom_collection.html' with item_slug=custom_collection_type.slug item_type='customcollection' %}
            {% endif %}
        {% endif %}
    </div>

    <br>

    <div class="d-flex justify-content-between">
        <h4 class="mb-0">My Cart</h4>
        {% if number_of_items %}
            <div class="d-flex align-items-center text-muted">
                <small class="price" style="font-size:18px;">
                    {{ number_of_items }} {% if number_of_items == 1 %}item{% else %}items{% endif %}
                </small>
            </div>
        {% endif %}
    </div>
    <hr>

    {% if number_of_items %}
        <div id="cart_items">
            {% for item in cart.cart_items.all %}
                <div class="d-flex justify-content-between">
                    {% if item.item_type.name == 'Macaron Custom Collection' %}
                        {% include 'partials/images_carousel.html' with images=item.content_object.get_featured_images width="100px" height="100px" %}
                    {% else %}
                        {% if item.content_object.get_featured_image %}
                            <div class="cart_sidebar_product_image">
                                <img src="{{ item.content_object.get_featured_image.picture.url }}"
                                     alt="{{ item.content_object.get_featured_image.alt_text }}"
                                     title="{{ item.content_object.get_featured_image.alt_text }}"
                                     class="rounded shadow border-tiffany">
                            </div>
                        {% endif %}
                    {% endif %}
                    <div class="p-0">
                        {% include 'partials/remove_from_cart.html' with item_slug=item.slug item_name=item.content_object.get_name %}
                    </div>
                </div>
                <div class="align-self-start mt-2">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="col-8">
                            <h5 class="mb-0" style="font-size: 17px;">{{ item.content_object.get_name }} <small
                                    class="text-muted">x {{ item.quantity }}</small></h5>
                        </div>
                        <div class="col-3 text-end">
                            <span class="price" style="font-size:22px;">{{ item.display_total }}</span>
                        </div>
                    </div>
                </div>
                {% if not forloop.last %}
                    <hr class="regular mt-2">
                {% endif %}
            {% endfor %}
        </div>
        <hr class="regular mt-2">
        <div class="d-flex flex-column align-items-end">
            <div class="mt-0 d-flex align-items-center">
                <h4 class="mb-0">Total: </h4> &nbsp;&nbsp;&nbsp;
                <span class="price" style="font-size:24px;">{{ cart.display_total }}</span>
            </div>
        </div>
        <div class="d-flex justify-content-between mt-3">
            <a href="{% url 'cart:view' %}" class="btn btn-outline-secondary">View Cart &nbsp;<i class="bi bi-cart"></i></a>
            {% include 'partials/request_checkout.html' %}
        </div>
    {% else %}
        <p>No items.</p>
    {% endif %}

</div>

cart/templates/partials/confirm_checkout.html
{# confirm checkout form #}
<form action="{% url 'cart:checkout_confirm' %}" method="POST">
    {% csrf_token %}
    <div class="g-recaptcha mb-3" data-sitekey="{{ GOOGLE_RECAPTCHA_SITE_KEY }}"></div>
    <div class="d-flex justify-content-md-end justify-content-between">
        <div class="d-block d-md-none d-lg-none">
            <a href="{% url 'cart:view' %}" class="btn btn-outline-secondary">
                <i class="bi bi-chevron-left"></i> &nbsp;Back to Cart &nbsp;<i class="bi bi-cart"></i>
            </a>
        </div>
        <button class="btn btn-primary" type="submit">Place Order &nbsp;<i class="bi bi-chevron-right"></i></button>
    </div>
</form>

cart/templates/partials/remove_from_cart.html
{# Remove from cart partial template #}
{# REQUIRED: item [maracron_set or collection instance] #}
<form action="{% url 'cart:remove_from_cart' item_slug %}" method="POST" id="remove_from_cart_form">
    {% csrf_token %}
    <input type="hidden" name="item_type" value="{{ item_type }}">
    {# trigger close button link to act like a submit button #}
    <a href="javascript:{}" onclick="document.getElementById('remove_from_cart_form').submit(); return false;"
       data-bs-toggle="tooltip" data-bs-placement="bottom" title="Remove {{ item_name }}">
        <i class='bi bi-x delicious-red' style='font-size:25px;'></i>
    </a>
</form>

cart/templates/partials/request_checkout.html
{# Checkout button form #}
<form action="{% url 'cart:checkout_request' %}" method="POST">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit" title="Proceed to checkout" data-bs-toggle="tooltip"
            data-bs-placement="bottom">Checkout &nbsp;<i class="bi bi-chevron-right"></i></button>
</form>